routes:
  ping:
    trust_required: any
    ttl: 1
    auth: optional
  message:
    trust_required: peer
    ttl: 2
    auth: optional
  town_square_bundle:
    trust_required: peer
    ttl: 2
    auth: optional
  response:
    trust_required: peer
    ttl: 2
    auth: optional
